### PR TITLE
soong: Disable clang-tidy

### PR DESCRIPTION
**Pull request by xNombre**
Build times go brrrrr

### CODE REVIEW

**Comment by neobuddy89** [comment]
what does this change apart from build time? performance impact?

**Comment by xNombre** [comment]
It's a code checker feature, doesn't impact performance at all. It just wastes time during build.

**Comment by gwolf2u** [comment]
@crdroidandroid/maintainers can you please test this one
willing to hear if there are any downsides

**Review by uixdess — APPROVED** [review]
LGTM

**Comment by xNombre** [comment]
Ive clean built without problems

**Comment by uixdess** [comment]
Before: clean build with ccache - 2h 7min
After: clean build with ccache - 2h 2min

**Comment by jomadeto** [comment]
Before: clean build with ccache 1h 32 min
After: clean build with ccache 1h 34 min, try again 1 h 33 min

Both builds without problems

**Comment by gwolf2u** [comment]
for me doesn't change much on build time, but I see no regression
ready to merge tag from me

**Review by gwolf2u — APPROVED** [review]

**Comment by neobuddy89** [comment]
if it doesnt change build time significantly, is there need to merge this and deviate?

**Comment by gwolf2u** [comment]
> if it doesnt change build time significantly, is there need to merge this and deviate?

Might help with low end servers
I see reason there

**Review by neobuddy89 — APPROVED** [review]

**Pull request merged**
